hiih

diff --git a/.github/workflows/gh-pages.yml b/.github/workflows/gh-pages.yml
--- a/.github/workflows/gh-pages.yml
+++ b/.github/workflows/gh-pages.yml
@@ -29,109 +29,26 @@ jobs:
       #   with:
       #     name: dotnet-format-results
       #     path: format-results.txt
-    
 
-  SonarCloud :
-    name: SonarCloud Analysis
-    runs-on: windows-latest
+  sonarcloud:
+    name: SonarCloud Scan
+    runs-on: ubuntu-latest
     steps:
-      - name: Set up JDK 17
-        uses: actions/setup-java@v3
+      - uses: actions/checkout@v2
+
+      - name: Set up Python
+        uses: actions/setup-python@v2
         with:
-          java-version: 17
-          distribution: 'zulu' # Alternative distribution options are available.
-      - uses: actions/checkout@v3
-        with:
-          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
+          python-version: '3.9' 
       
-      # Installing the correct version of .NET SDK
-      - name: Setup .NET Core SDK
-        uses: actions/setup-dotnet@v3
-        with:
-          dotnet-version: '8.0.x'
-
-      - name: Setup Python
-        uses: actions/setup-python@v3
-        with:
-          python-version: '3.10'
-
-      - name: Install Python dependencies
+      - name: Install dependencies
         run: |
           python -m pip install --upgrade pip
           pip install -r tests/server.Tests/requirements.txt
-      
-      - name: Cache SonarCloud packages
-        uses: actions/cache@v3
-        with:
-          path: ~\sonar\cache
-          key: ${{ runner.os }}-sonar
-          restore-keys: ${{ runner.os }}-sonar
-      
-      - name: Cache SonarCloud scanner
-        id: cache-sonar-scanner
-        uses: actions/cache@v3
-        with:
-          path: .\.sonar\scanner
-          key: ${{ runner.os }}-sonar-scanner
-          restore-keys: ${{ runner.os }}-sonar-scanner
-      
-      - name: Install SonarCloud scanner
-        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
-        shell: powershell
-        run: |
-          New-Item -Path .\.sonar\scanner -ItemType Directory
-          dotnet tool update dotnet-sonarscanner --tool-path .\.sonar\scanner
-      
-      # Install dotcover for code coverage
-      - name: Install dotCover
-        run: dotnet tool install --global JetBrains.dotCover.GlobalTool
 
-      # SonarCloud analysis begins
-      - name: Begin SonarCloud Analysis
-        run: .\.sonar\scanner\dotnet-sonarscanner begin /k:"whizdor_CS455_Tinker" /o:"whizdor" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.cs.dotcover.reportsPaths=dotCover.Output.html /d:sonar.exclusions="**/dotCover.Output/**,dotCover.Output.html"
-
-      # Build the solution after starting SonarCloud analysis
-      - name: Build the solution
-        run: dotnet build client/StackNServe.csproj --configuration Debug
-
-      # Build the test project explicitly to generate test DLLs
-      - name: Build the test project
-        run: dotnet build tests/client.Tests/ --configuration Debug
-
-      # Run tests and collect coverage
-      - name: Run tests and collect coverage
-        run: |
-          dotnet dotcover test tests/client.Tests/StackNServe.Tests.csproj --dcReportType=HTML > test-results.txt
-          cat test-results.txt
-
-       # Run Python server tests and collect coverage
-      - name: Run Python tests and collect coverage
+      - name: Run tests and generate coverage report
         run: |
           pytest tests/server.Tests --cov=server --cov-report xml:coverage.xml
-
-      # Upload unit test results and coverage reports as artifacts
-      - name: Upload Unit Test and Coverage Results
-        if: always()
-        uses: actions/upload-artifact@v3
-        with:
-          name: test-results
-          path: test-results.txt                 
-
-      # Finalize the SonarCloud analysis after building the project
-      - name: End SonarCloud Analysis
-        run: .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
-
-      # # Fetch detailed SonarCloud results and output in the logs
-      # - name: Fetch and display detailed SonarCloud analysis results
-      #   if: always()
-      #   shell: bash
-      #   env:
-      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-      #   run: |
-      #     echo "Fetching detailed analysis results..."
-      #     curl -u $SONAR_TOKEN: "https://sonarcloud.io/api/issues/search?componentKeys=whizdor_CS455_Tinker" > sonarcloud-results.json
-      #     echo "Analysis results:"
-      #     cat sonarcloud-results.json | jq '.issues[] | {key, component, severity, message, line}' 
 
       - name: SonarCloud Scan
         uses: SonarSource/sonarcloud-github-action@master
@@ -139,76 +56,191 @@ jobs:
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
         with:
           args: >
-            -Dsonar.projectKey=whizdor_CS455_Tinker
-            -Dsonar.organization=whizdor
-            -Dsonar.sources=server
-            -Dsonar.language=py
-            -Dsonar.coverageReportPaths=coverage.xml
+  #           -Dsonar.projectKey=whizdor_CS455_Tinker
+  #           -Dsonar.organization=whizdor
+  #           -Dsonar.sources=server
+  #           -Dsonar.language=py
+  #           -Dsonar.coverageReportPaths=coverage.xml
 
-      # # Upload the SonarCloud results JSON as an artifact
-      # - name: Upload SonarCloud results artifact
-      #   if: always()  
-      #   uses: actions/upload-artifact@v3
-      #   with:
-      #     name: sonarcloud-results
-      #     path: sonarcloud-results.json 
 
-      # - name: Check SonarCloud Quality Gate
-      #   id: quality-gate
-      #   shell: bash
-      #   env:
-      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-      #   run: |
-      #     SONAR_STATUS=$(curl -s -u $SONAR_TOKEN: "https://sonarcloud.io/api/qualitygates/project_status?projectKey=whizdor_CS455_Tinker" | jq -r '.projectStatus.status')
-      #     if [ "$SONAR_STATUS" != "OK" ]; then
-      #       echo "Quality gate failed: $SONAR_STATUS"
-      #       exit 1
-      #     else
-      #       echo "Quality gate passed!"
-      #     fi
+  # SonarCloud :
+  #   name: SonarCloud Analysis
+  #   runs-on: windows-latest
+  #   steps:
+  #     - name: Set up JDK 17
+  #       uses: actions/setup-java@v3
+  #       with:
+  #         java-version: 17
+  #         distribution: 'zulu' # Alternative distribution options are available.
+  #     - uses: actions/checkout@v3
+  #       with:
+  #         fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
+      
+  #     # Installing the correct version of .NET SDK
+  #     - name: Setup .NET Core SDK
+  #       uses: actions/setup-dotnet@v3
+  #       with:
+  #         dotnet-version: '8.0.x'
 
-  deploy-to-github-pages:
-    needs: [SonarCloud, dotnetformat]
-    runs-on: ubuntu-latest
-    if: success()
-    steps:
-    # Checkout the code from the master branch
-    - uses: actions/checkout@v3
+  #     - name: Setup Python
+  #       uses: actions/setup-python@v3
+  #       with:
+  #         python-version: '3.10'
+
+  #     - name: Install Python dependencies
+  #       run: |
+  #         python -m pip install --upgrade pip
+  #         pip install -r tests/server.Tests/requirements.txt
+      
+  #     - name: Cache SonarCloud packages
+  #       uses: actions/cache@v3
+  #       with:
+  #         path: ~\sonar\cache
+  #         key: ${{ runner.os }}-sonar
+  #         restore-keys: ${{ runner.os }}-sonar
+      
+  #     - name: Cache SonarCloud scanner
+  #       id: cache-sonar-scanner
+  #       uses: actions/cache@v3
+  #       with:
+  #         path: .\.sonar\scanner
+  #         key: ${{ runner.os }}-sonar-scanner
+  #         restore-keys: ${{ runner.os }}-sonar-scanner
+      
+  #     - name: Install SonarCloud scanner
+  #       if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
+  #       shell: powershell
+  #       run: |
+  #         New-Item -Path .\.sonar\scanner -ItemType Directory
+  #         dotnet tool update dotnet-sonarscanner --tool-path .\.sonar\scanner
+      
+  #     # Install dotcover for code coverage
+  #     - name: Install dotCover
+  #       run: dotnet tool install --global JetBrains.dotCover.GlobalTool
+
+  #     # SonarCloud analysis begins
+  #     - name: Begin SonarCloud Analysis
+  #       run: .\.sonar\scanner\dotnet-sonarscanner begin /k:"whizdor_CS455_Tinker" /o:"whizdor" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.cs.dotcover.reportsPaths=dotCover.Output.html /d:sonar.exclusions="**/dotCover.Output/**,dotCover.Output.html"
+
+  #     # Build the solution after starting SonarCloud analysis
+  #     - name: Build the solution
+  #       run: dotnet build client/StackNServe.csproj --configuration Debug
+
+  #     # Build the test project explicitly to generate test DLLs
+  #     - name: Build the test project
+  #       run: dotnet build tests/client.Tests/ --configuration Debug
+
+  #     # Run tests and collect coverage
+  #     - name: Run tests and collect coverage
+  #       run: |
+  #         dotnet dotcover test tests/client.Tests/StackNServe.Tests.csproj --dcReportType=HTML > test-results.txt
+  #         cat test-results.txt
+
+  #      # Run Python server tests and collect coverage
+  #     - name: Run Python tests and collect coverage
+  #       run: |
+  #         pytest tests/server.Tests --cov=server --cov-report xml:coverage.xml
+
+  #     # Upload unit test results and coverage reports as artifacts
+  #     - name: Upload Unit Test and Coverage Results
+  #       if: always()
+  #       uses: actions/upload-artifact@v3
+  #       with:
+  #         name: test-results
+  #         path: test-results.txt                 
+
+  #     # Finalize the SonarCloud analysis after building the project
+  #     - name: End SonarCloud Analysis
+  #       run: .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
+
+  #     # # Fetch detailed SonarCloud results and output in the logs
+  #     # - name: Fetch and display detailed SonarCloud analysis results
+  #     #   if: always()
+  #     #   shell: bash
+  #     #   env:
+  #     #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+  #     #   run: |
+  #     #     echo "Fetching detailed analysis results..."
+  #     #     curl -u $SONAR_TOKEN: "https://sonarcloud.io/api/issues/search?componentKeys=whizdor_CS455_Tinker" > sonarcloud-results.json
+  #     #     echo "Analysis results:"
+  #     #     cat sonarcloud-results.json | jq '.issues[] | {key, component, severity, message, line}' 
+
+  #     - name: SonarCloud Scan
+  #       uses: SonarSource/sonarcloud-github-action@master
+  #       env:
+  #         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+  #       with:
+  #         args: >
+  #           -Dsonar.projectKey=whizdor_CS455_Tinker
+  #           -Dsonar.organization=whizdor
+  #           -Dsonar.sources=server
+  #           -Dsonar.language=py
+  #           -Dsonar.coverageReportPaths=coverage.xml
+
+  #     # # Upload the SonarCloud results JSON as an artifact
+  #     # - name: Upload SonarCloud results artifact
+  #     #   if: always()  
+  #     #   uses: actions/upload-artifact@v3
+  #     #   with:
+  #     #     name: sonarcloud-results
+  #     #     path: sonarcloud-results.json 
+
+  #     # - name: Check SonarCloud Quality Gate
+  #     #   id: quality-gate
+  #     #   shell: bash
+  #     #   env:
+  #     #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+  #     #   run: |
+  #     #     SONAR_STATUS=$(curl -s -u $SONAR_TOKEN: "https://sonarcloud.io/api/qualitygates/project_status?projectKey=whizdor_CS455_Tinker" | jq -r '.projectStatus.status')
+  #     #     if [ "$SONAR_STATUS" != "OK" ]; then
+  #     #       echo "Quality gate failed: $SONAR_STATUS"
+  #     #       exit 1
+  #     #     else
+  #     #       echo "Quality gate passed!"
+  #     #     fi
+
+  # deploy-to-github-pages:
+  #   needs: [SonarCloud, dotnetformat]
+  #   runs-on: ubuntu-latest
+  #   if: success()
+  #   steps:
+  #   # Checkout the code from the master branch
+  #   - uses: actions/checkout@v3
     
-    # Setup .NET Core SDK
-    - name: Setup .NET Core SDK
-      uses: actions/setup-dotnet@v3
-      with:
-        dotnet-version: 8.0.107
+  #   # Setup .NET Core SDK
+  #   - name: Setup .NET Core SDK
+  #     uses: actions/setup-dotnet@v3
+  #     with:
+  #       dotnet-version: 8.0.107
 
-    # Publish the project
-    - name: Publish .NET Core Project
-      run: dotnet publish src/StackNServe/StackNServe.csproj -c Release -o release --nologo
+  #   # Publish the project
+  #   - name: Publish .NET Core Project
+  #     run: dotnet publish src/StackNServe/StackNServe.csproj -c Release -o release --nologo
     
-    # Verify that index.html exists after the publish
-    - name: Verify index.html exists
-      run: |
-        if [ ! -f release/wwwroot/index.html ]; then
-          echo "Error: index.html not found!"
-          exit 1
-        fi
+  #   # Verify that index.html exists after the publish
+  #   - name: Verify index.html exists
+  #     run: |
+  #       if [ ! -f release/wwwroot/index.html ]; then
+  #         echo "Error: index.html not found!"
+  #         exit 1
+  #       fi
 
-    # Change base tag in index.html to point to the correct subdirectory (StackNServe)
-    - name: Change base-tag in index.html
-      run: sed -i 's/<base href="\/" \/>/<base href="\/CS455_Tinker\/" \/>/g' release/wwwroot/index.html
+  #   # Change base tag in index.html to point to the correct subdirectory (StackNServe)
+  #   - name: Change base-tag in index.html
+  #     run: sed -i 's/<base href="\/" \/>/<base href="\/CS455_Tinker\/" \/>/g' release/wwwroot/index.html
     
-    # Copy index.html to 404.html for GitHub Pages fallback routing
-    - name: Copy index.html to 404.html
-      run: cp release/wwwroot/index.html release/wwwroot/404.html
+  #   # Copy index.html to 404.html for GitHub Pages fallback routing
+  #   - name: Copy index.html to 404.html
+  #     run: cp release/wwwroot/index.html release/wwwroot/404.html
 
-    # Add a .nojekyll file to prevent Jekyll processing
-    - name: Add .nojekyll file
-      run: touch release/wwwroot/.nojekyll
+  #   # Add a .nojekyll file to prevent Jekyll processing
+  #   - name: Add .nojekyll file
+  #     run: touch release/wwwroot/.nojekyll
 
-    # Deploy the wwwroot folder to the gh-pages branch
-    - name: Deploy to GitHub Pages
-      uses: JamesIves/github-pages-deploy-action@3.7.1
-      with:
-        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        BRANCH: gh-pages
-        FOLDER: release/wwwroot
+  #   # Deploy the wwwroot folder to the gh-pages branch
+  #   - name: Deploy to GitHub Pages
+  #     uses: JamesIves/github-pages-deploy-action@3.7.1
+  #     with:
+  #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  #       BRANCH: gh-pages
+  #       FOLDER: release/wwwroot
